from fpdf import FPDF
import datetime

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'CyberRescue Incident Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")} | Page {self.page_no()}', 0, 0, 'C')

def generate_report_pdf(user_id, username, incident_type, metadata_dict, date, filename):
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Basic Info
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "1. User Information", 1, 1, 'L', 1)
    pdf.cell(0, 10, f"User ID: {user_id}", 0, 1)
    pdf.cell(0, 10, f"Name/Username: {username}", 0, 1)
    pdf.ln(5)

    # Incident Info
    pdf.cell(0, 10, "2. Incident Overview", 1, 1, 'L', 1)
    pdf.cell(0, 10, f"Main Category: {incident_type}", 0, 1)
    pdf.cell(0, 10, f"Date of Incident: {date}", 0, 1)
    pdf.ln(5)

    # Branched Details (Forensic Metadata)
    pdf.cell(0, 10, "3. Forensic Details", 1, 1, 'L', 1)
    for key, value in metadata_dict.items():
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(40, 10, f"{key}:", 0, 0)
        pdf.set_font("Arial", size=11)
        pdf.cell(0, 10, f"{value}", 0, 1)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, "This report is generated by CyberRescue Bot. Please submit this along with screenshots to your nearest Cyber Cell or on cybercrime.gov.in.")

    pdf.output(filename)
